### PR TITLE
Composeable templated GTFSIterator replaces existing Iterators

### LINKED ISSUE #2: Improve ergonomics of adding new iterators
Adding the new iterators was kind of a drag, in particular there is a lot of generic boiler plate stuff.

I've made a prototype of what this might look like in https://github.com/medwards/transitfeed/blob/dff5d12de20c1d4f016ea0cb55ab0b15a9c756f2/src/gtfs/stop_times.rs and would like your feedback.

Basically GTFSIterator accepts a Csv like it does now but also a parsing function that it applies during the iteration.

GTFSIterator would end up in gtfs/gtfs.rs or gtfs/mod.rs and I'm thinking of adding a function that does the composition for you if you pass the filepath. I also want to move error capturing/transformation up to GTFSIterator.next instead of it happening in various places (value parsing functions, etc.)

Let me know what you think!

### PR DESCRIPTION
**Pull request by medwards**
Fixes #2

There's a couple of things I'd like feedback on:
I see why the commented out GTFSIterator.from_path doesn't compile, but I still really want something like this. Do you have any ideas?
There much ugliness in the Error implementation for ParseError. I'm sure there is a better way to do this but I'm new to Rust.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1bd9a2c4968adb95eb77814d4edf95d3148c3745
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: fddf76ea9b025f02237d4af1d0b5cf9ad3fec24e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 94c3f3dcca5742a7a9ebe74ef34eb7e80c5ee47b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ef672c99d477bfcccb54f7370325f291bc09aeb8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/bfrog/transitfeed

---
This message was auto-generated by https://gitcop.com

**Comment by medwards** [comment]
@bfrog: I could still use a code review on this.

**Comment by bfrog** [comment]
thanks for the ding, will look now

**Comment by bfrog** [comment]
So my only concern is the removal of describing where parse errors occur in the gtfs txt files, which I found useful previously. Some GTFS providers do funny and odd things that aren't a part of the standard. Other than that the work looks great! I'd really appreciate the file/line/error kind be the tuple when relating to errors. If I see that back in I'd gladly merge this.

**Comment by bfrog** [comment]
I apologize, I didn't see that you have since wrapped ParseError in a LineError :+1: 

In terms of removing some of the ugliness from ParseError and Error handling in general here saner, perhaps using the error-chain crate would greatly help.

**Comment by bfrog** [comment]
GTFSIterator::from_path is interesting but I don't think its possible to do in Rust without erasing the type specialization of the parse fn and the GTFSIterator itself using an enum to contain all possible iterable types like Calendar, Trip, Stop, etc which really defeats the type safety.

Now that doesn't mean you can't do what you want to do at all, but to do it you would likely need to write a macro!

Ex:

gtfs_iter_for_file!("stops.txt")

I'll leave that to you to have fun working out if you are still interested in writing such a thing

**Comment by bfrog** [comment]
There are quite a few warnings when compiling this as well, just a heads up those should be corrected to the best of your abilities

**Comment by medwards** [comment]
I'll get to most of this this tonight at the Rust co-working thing here.
* I'm a stickler for good names, so would LineParsingError be a better name? I think maybe LineError was too terse which led to the misunderstanding
* I'm going to defer a from_path like macro to another PR (I get headaches whenever I read macro definitions right now and have some other ideas I want to wrap up)
* glanced at error-chain: It would clean up those match arms by just making the errors based on strings right? Otherwise I'm not clear on how it helps. Also if there isn't a Rust std based way to improve the current errors I will leave it as is and treat error-chain as a separate improvement for now.
* I have a bunch of unused code warnings and other cleanups in my private branch that I'll try to tear out and include here. I'll probably also do a rust fmt pass unless you have objections.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7e03bbaf376a5934f1adfe2a439c34b20ca0b877
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a2928255b0eabb264dc9c2149acb57e45c5d2f27
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 36ca55b775081697796be0cfe6f80290aacdef51
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d3d30368b2a3f84da3a219d6a546f06a656e004a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8afbf1862bd7fc74234217a05f4106ef69db68d8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 11ab8f4aee755892d0c96e458b37a6eadb6a819d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 912a3cee8e364e807578f7efe39113f2db179c5d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b145ebbca01f9e55d7a7b8ea1a74984c989ef575
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/bfrog/transitfeed

---
This message was auto-generated by https://gitcop.com

**Comment by medwards** [comment]
This took awhile to rebase so didn't get to my rust fmt run.
* Moved test data to examples/bench from examples (I want to add more integration test data to that folder, specifically these https://github.com/google/transitfeed/tree/master/tests/data )
* Added a bunch of tests, and the existing tests are better (ie checking that we don't get Err on the sample data). Also caught and fixed a bug in the line number count.

Could we please turn off gitcop?

**Comment by bfrog** [comment]
I would suggest lets get this in first then run rust-fmt

gitcop is pretty easy to follow and enforces some relatively simple rules for commit messages that I've already followed for the repo, if its a real downer I can turn it off, otherwise really this could be rebased and the message began with refactor: short desc and gitcop would be happy

**Comment by medwards** [comment]
Changed LineError to LineParseError

**Comment by medwards** [comment]
OK at this point things are conceptually complete. I was missing a way to unit test parse_row functions. The last month I worked on adding even more generics so that parse_row functions could accept arbitrary zipped iterators instead of the concrete classes it currently accepts.

This turned out to be extremely painful and instead I created a parse_row_harness test helper that makes the concrete iterator for you from normal vectors. It has to also call parse_row because of lifetime issues that I didn't see an obvious workaround for.

What can I do to help get this merged, or clarify why its not going forward? (ie maybe you're really set on going straight to the csv crate?)

**Comment by bfrog** [comment]
Looks good!

**Pull request merged**
